// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqnnyyoihdcupkdzqnxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxbm55eW9paGRjdXBrZHpxbnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Nzc5NTUsImV4cCI6MjA3MTI1Mzk1NX0.gEkq3Zc8j0XPHKRwxxi3G-ev6JWUV8NleOKZma_X68s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});